- sections:
  - title: Getting Started
    link: /docs/getting-started.md
    open: true
    articles:
      - title: Welcome to Reporting
        link: /docs/getting-started.md
  - title: Documentation
    link: /docs/getting-started/overview.md
    open: true
    articles:
      - title: Documentation
        link: /docs/getting-started.md
  - title: Tutorials
    open: true
    link: /docs/getting-started.md
    articles:
      - title: Tutorials
        link: /docs/getting-started.md
