header:
  productName: Reporting
  productionDescription: Fiserv Reporting allows the consumer the ability to fine tune their analytics to fit their own unique needs. By leveraging itemized data or summarized models through our easy to use APIs the consumer can track sales on a grandular level. Analyze payment processing with an easy-to-use suite of online tools, gaining greater insight to quickly and effectively manage your electronic transactions.
  image: 
    link: "/assets/images/clx_image.png"
    altText: Reporting
steps:  
  learnSteps:
    - title: Learn
      description: >
        This is a very long sentence
        that spans several lines in the YAML
        but which will be rendered as a string
        with only a single carriage return appended to the end.
    - title:
      description:
      link:
    - title:
      description:
      link:
  buildSteps:
    - title:
      description:
      link:
    - title:
      description:
      link:
    - title:
      description:
      link:
  validateSteps:
    - title:
      description:
      link:
    - title:
      description:
      link:
    - title:
      description:
      link:
  deploySteps:
    - title:
      description:
      link:
    - title:
      description:
      link:
    - title:
      description:
      link:
benefits:
  - title: API Integration
    description: Leverage easy to use tools to pull in data for real time insight into customer behavior. Get up and running quickly an easily with or sample processes. 
  - title: Real Time Data
    description: Create your own tracking applications with relevant real time data for your business. Utilize actual metrics to create on site dashboards with your own design and brand for an improved customer experience.
  - title: Checklist
    description: Leverage our checklist to assure you have what you need for a complete integration into Reporting APIs.
featuredFeatures:
  - title: Sample Integrations
    description: Integrate with our easy to use API tool set for clear reporting purposes. Utilize the sample request/responses to gain a better understanding our of API ecosystem. 
    tags: ["Enterprise"]
    bullets:
      bullet1: Browse working examples of our integrations. 
      bullet2: Leverage easy to use tools to pull in data for real time insight into customer behavior.
      bullet3: Get up and running quickly an easily with or sample processes. 
    links:
      link1: "/docs/APIs/sample-api.md"
  - title: API Reference
    description: With clearly defined object data types and an industry standard json paradiam, our restful APIs speed the delivery cycle of your application development. 
    tags: ["Enterprise"]
    bullets:
      bullet1: Learn more about our API objects, methods, requests and responses. 
    links:
      link1: "/docs/APIs/api-model.md"
  - title: Security
    description: Security is at the heart of what we do as a company. Leverage our secure integrations to open up key metrics for your customer base.
    tags: ["Enterprise"]
    bullets:
      bullet1: Create, manage and utilize developer api tokens in order to protect customer data.
      bullet2: Uniquely identify and track developer access.
      bullet3: Grant accessibilty to only those groups who it is required. 
    links:
      link1: "/docs/Security/security.md"
featuredAPIs: ["payments", "orders", "cancel"]
useCases:
  - title:
    subtitle:
    description:
    link:
  - title:
    subtitle:
    description:
    link:
