header:
  productName: Reporting
  productionDescription: Fiserv Reporting allows the consumer the ability to fine tune their analytics to fit their own unique needs. By leveraging itemized data or summarized models through our easy to use APIs the consumer can track sales on a grandular level. Analyze payment processing with an easy-to-use suite of online tools, gaining greater insight to quickly and effectively manage your electronic transactions.
  image: 
    link: "/assets/images/reporting.jpg"
    altText: Reporting
steps:  
  learnSteps:
    - title: Learn
      description: >
        This is a very long sentence
        that spans several lines in the YAML
        but which will be rendered as a string
        with only a single carriage return appended to the end.
    - title:
      description:
      link:
    - title:
      description:
      link:
  buildSteps:
    - title:
      description:
      link:
    - title:
      description:
      link:
    - title:
      description:
      link:
  validateSteps:
    - title:
      description:
      link:
    - title:
      description:
      link:
    - title:
      description:
      link:
  deploySteps:
    - title:
      description:
      link:
    - title:
      description:
      link:
    - title:
      description:
      link:
benefits:
  - title:
    description:
  - title:
    description:
  - title:
    description:
featuredFeatures:
  - title:
    description:
    tags: ["Enterprise", "Airline"]
    bullets:
      bullet1: asdfadsfasdfasdfasdfsadfasdfasdfadsfadsfasd
      bullet2: asdfasdfadsfasdfadsfsadfadsfasdfadsfadsfadsfasdfasdfasdfasdf
    links:
      link1: "/docs/getting-started/getting-started.md"
  - title:
    description:
    tags: ["Enterprise", "Airline"]
    bullets:
      bullet1: asdf
      bullet2: asdf
    links:
      link1: "/docs/getting-started/getting-started.md"
featuredAPIs: ["payments", "orders", "cancel"]
useCases:
  - title:
    subtitle:
    description:
    link:
  - title:
    subtitle:
    description:
    link:
